apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manage-clusters
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://10.188.159.34:6443
  source:
    repoURL: https://github.com/willislin0206/argoCD-test.git
    targetRevision: HEAD
    path: manifest/clusters/c02
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      
      