apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manage-clusters-02
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://10.188.159.34:6443
  source:
    repoURL: https://github.com/willislin0206/argoCD-test.git
    targetRevision: HEAD
    path: argo/tw/cluster02/resources
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"

 
      
