apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: app01-

resources:
  - ../../base/

patches:
  - path: ./overlays/app01/deployment-patch.yaml
  - path: ./overlays/app02/deployment-patch.yaml  
  
#patchesStrategicMerge:
#  - deployment-patch.yaml
